ec2django/urls.py
from django.contrib import admin
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static #

urlpatterns = [
	path('', include('poll.urls')),
	path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
	path('chat_channel/', include('chat_channel.urls')),
	# path('ref_pages/', include('ref_pages.urls')),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.urls import path

from . import views
app_name = 'poll'


urlpatterns = [
	path('', views.all, name='all'),
	# path('chat/', views.chat, name='chat'),
	path('basicview/1', views.template_two, name='template_two'),
	path('support', views.support, name='support'),
	path('unique', views.unique, name='unique'),
	path('calculator', views.calculator, name='calculator'),
	path('script', views.order, name='order'),
    path('poll/', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
	path('articles/all/', views.articles, name='articles'),
	path('articles/get/<int:article_id>', views.article, name='article'),

]

poll/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.db.models import TextField
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
	
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
	
    def __str__(self):
        return self.choice_text


class Phonebase(models.Model):
    phone_persone = models.CharField(max_length=30)
    reg_date = models.DateTimeField('date published')
    name_persone = models.CharField(max_length=200)

    def __str__(self):
        return self.phone_persone

class Tank(models.Model):
    diz_top = models.IntegerField(default=0)
    tank_amm = models.IntegerField(default=23)
    tank_name = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')
    crew = models.IntegerField(default=3)



class Article(models.Model):
    class Meta():
        db_table = "article"

    article_title = models.CharField(max_length=200)
    article_text = models.TextField()
    article_date = models.DateTimeField()
    article_like = models.IntegerField(default=0)
    article_image = models.ImageField()



class Comments(models.Model):
    class Meta():
        db_table = "comments"

    comments_text = models.TextField()
    comments_article = models.ForeignKey(Article,on_delete=models.PROTECT)


class Unique_set(models.Model):
    UserAgent = models.TextField()
    IP_user = models.CharField(max_length=50)

    def __str__(self):
        return self.IP_user

# class Post(models.Model):
#     title = models.TextField()  # type:
#     cover = models.ImageField(upload_to='images/')
#
#     def __str__(self):
#         return self.title

poll/forms.py
from django import forms

class ChatForm(forms.Form):
    your_name = forms.CharField()

# class UploadFileForm(forms.Form):
#     file = forms.ImageField()


# def handle_uploaded_file(f):
#     with open('/home/usr/PycharmProjects/NewProject/uploads/ss.img', 'wb+') as destination:
#         for chunk in f.chunks():
#             destination.write(chunk)

poll/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Choice, Question, Phonebase, Article, Comments, Unique_set
from .forms import ChatForm
import nltk
from nltk.stem.lancaster import LancasterStemmer

# Для загрузки файла

stemmer = LancasterStemmer()
import random
import json
import requests

def calculator(request):
    return render(request, 'poll/calculator.html')


def support(request):
    contact_list = Phonebase.objects.all()
    paginator = Paginator(contact_list, 2)  # Show 25 contacts per page
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request, 'poll/support.html', {'contacts': contacts})


def Tank(request):
    contact_list = Tank.objects.all()
    paginator = Paginator(contact_list, 2)  # Show 25 contacts per page
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request, 'poll/support.html', {'contacts': contacts})


def order(request):
    return render(request, 'poll/order.html')


def unique(request):
    return render(request, 'poll/unique.html')





class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))


"""CHAT"""
#
#
# def bag_of_words(s, words):
#     bag = [0 for _ in range(len(words))]
#
#     s_words = nltk.word_tokenize(s)
#     s_words = [stemmer.stem(word.lower()) for word in s_words]
#
#     for se in s_words:
#         for i, w in enumerate(words):
#             if w == se:
#                 bag[i] = 1
#
#     return numpy.array(bag)
#
#
# MODEL = None
#
# def get_model():
#     global MODEL
#     if MODEL is None:
#         words, labels, training, output = get_hdata()
#         net = tflearn.input_data(shape=[None, len(training[0])])
#         net = tflearn.fully_connected(net, 8)
#         net = tflearn.fully_connected(net, 8)
#         net = tflearn.fully_connected(net, len(output[0]), activation="softmax")
#         net = tflearn.regression(net)
#
#         MODEL = tflearn.DNN(net)
#         MODEL.load("model.tflearn")
#     return MODEL
#
# DATAA = None
# def get_data():
#     global DATAA
#
#     if DATAA is None:
#         with open("intents.json") as file:
#             DATAA = json.load(file)
#     return DATAA
#
#
# HDATA = None
# def get_hdata():
#     global HDATA
#
#     if HDATA is None:
#         with open("data.pickle", "rb") as f:
#             HDATA = pickle.load(f)
#     return HDATA
#
#
# def chat(request):
#     out = "You need help?"
#     if "your_name" in request.POST:
#         words, labels, training, output = get_hdata()
#         results = get_model().predict([bag_of_words(request.POST["your_name"], words)])
#         results_index = numpy.argmax(results)
#         tag = labels[results_index]
#
#         for tg in get_data()["intents"]:
#             if tg['tag'] == tag:
#                 responses = tg['responses']
#         out = random.choice(responses)
#
#     return render(request, 'poll/chat.html',context={'name':out})

"""CHAT  END"""
def all(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
        user_agent = request.META.get('HTTP_USER_AGENT')
        name_host = request.META.get('SERVER_PORT')
        method = request.META.get('REQUEST_METHOD')
        try:
            get_country = requests.get("https://ipinfo.io/%s?token=77a09218c42d10" % ip)
            c = (get_country.json())
            t = {"BD": "Bangladesh", "BE": "Belgium", "BF": "Burkina Faso", "BG": "Bulgaria",
                 "BA": "Bosnia and Herzegovina", "BB": "Barbados", "WF": "Wallis and Futuna", "BL": "Saint Barthelemy",
                 "BM": "Bermuda", "BN": "Brunei", "BO": "Bolivia", "BH": "Bahrain", "BI": "Burundi", "BJ": "Benin",
                 "BT": "Bhutan", "JM": "Jamaica", "BV": "Bouvet Island", "BW": "Botswana", "WS": "Samoa",
                 "BQ": "Bonaire, Saint Eustatius and Saba ", "BR": "Brazil", "BS": "Bahamas", "JE": "Jersey",
                 "BY": "Belarus", "BZ": "Belize", "RU": "Russia", "RW": "Rwanda", "RS": "Serbia", "TL": "East Timor",
                 "RE": "Reunion", "TM": "Turkmenistan", "TJ": "Tajikistan", "RO": "Romania", "TK": "Tokelau",
                 "GW": "Guinea-Bissau", "GU": "Guam", "GT": "Guatemala",
                 "GS": "South Georgia and the South Sandwich Islands", "GR": "Greece", "GQ": "Equatorial Guinea",
                 "GP": "Guadeloupe", "JP": "Japan", "GY": "Guyana", "GG": "Guernsey", "GF": "French Guiana",
                 "GE": "Georgia", "GD": "Grenada", "GB": "United Kingdom", "GA": "Gabon", "SV": "El Salvador",
                 "GN": "Guinea", "GM": "Gambia", "GL": "Greenland", "GI": "Gibraltar", "GH": "Ghana", "OM": "Oman",
                 "TN": "Tunisia", "JO": "Jordan", "HR": "Croatia", "HT": "Haiti", "HU": "Hungary", "HK": "Hong Kong",
                 "HN": "Honduras", "HM": "Heard Island and McDonald Islands", "VE": "Venezuela", "PR": "Puerto Rico",
                 "PS": "Palestinian Territory", "PW": "Palau", "PT": "Portugal", "SJ": "Svalbard and Jan Mayen",
                 "PY": "Paraguay", "IQ": "Iraq", "PA": "Panama", "PF": "French Polynesia", "PG": "Papua New Guinea",
                 "PE": "Peru", "PK": "Pakistan", "PH": "Philippines", "PN": "Pitcairn", "PL": "Poland",
                 "PM": "Saint Pierre and Miquelon", "ZM": "Zambia", "EH": "Western Sahara", "EE": "Estonia",
                 "EG": "Egypt", "ZA": "South Africa", "EC": "Ecuador", "IT": "Italy", "VN": "Vietnam",
                 "SB": "Solomon Islands", "ET": "Ethiopia", "SO": "Somalia", "ZW": "Zimbabwe", "SA": "Saudi Arabia",
                 "ES": "Spain", "ER": "Eritrea", "ME": "Montenegro", "MD": "Moldova", "MG": "Madagascar",
                 "MF": "Saint Martin", "MA": "Morocco", "MC": "Monaco", "UZ": "Uzbekistan", "MM": "Myanmar",
                 "ML": "Mali", "MO": "Macao", "MN": "Mongolia", "MH": "Marshall Islands", "MK": "Macedonia",
                 "MU": "Mauritius", "MT": "Malta", "MW": "Malawi", "MV": "Maldives", "MQ": "Martinique",
                 "MP": "Northern Mariana Islands", "MS": "Montserrat", "MR": "Mauritania", "IM": "Isle of Man",
                 "UG": "Uganda", "TZ": "Tanzania", "MY": "Malaysia", "MX": "Mexico", "IL": "Israel", "FR": "France",
                 "IO": "British Indian Ocean Territory", "SH": "Saint Helena", "FI": "Finland", "FJ": "Fiji",
                 "FK": "Falkland Islands", "FM": "Micronesia", "FO": "Faroe Islands", "NI": "Nicaragua",
                 "NL": "Netherlands", "NO": "Norway", "NA": "Namibia", "VU": "Vanuatu", "NC": "New Caledonia",
                 "NE": "Niger", "NF": "Norfolk Island", "NG": "Nigeria", "NZ": "New Zealand", "NP": "Nepal",
                 "NR": "Nauru", "NU": "Niue", "CK": "Cook Islands", "XK": "Kosovo", "CI": "Ivory Coast",
                 "CH": "Switzerland", "CO": "Colombia", "CN": "China", "CM": "Cameroon", "CL": "Chile",
                 "CC": "Cocos Islands", "CA": "Canada", "CG": "Republic of the Congo", "CF": "Central African Republic",
                 "CD": "Democratic Republic of the Congo", "CZ": "Czech Republic", "CY": "Cyprus",
                 "CX": "Christmas Island", "CR": "Costa Rica", "CW": "Curacao", "CV": "Cape Verde", "CU": "Cuba",
                 "SZ": "Swaziland", "SY": "Syria", "SX": "Sint Maarten", "KG": "Kyrgyzstan", "KE": "Kenya",
                 "SS": "South Sudan", "SR": "Suriname", "KI": "Kiribati", "KH": "Cambodia",
                 "KN": "Saint Kitts and Nevis", "KM": "Comoros", "ST": "Sao Tome and Principe", "SK": "Slovakia",
                 "KR": "South Korea", "SI": "Slovenia", "KP": "North Korea", "KW": "Kuwait", "SN": "Senegal",
                 "SM": "San Marino", "SL": "Sierra Leone", "SC": "Seychelles", "KZ": "Kazakhstan",
                 "KY": "Cayman Islands", "SG": "Singapore", "SE": "Sweden", "SD": "Sudan", "DO": "Dominican Republic",
                 "DM": "Dominica", "DJ": "Djibouti", "DK": "Denmark", "VG": "British Virgin Islands", "DE": "Germany",
                 "YE": "Yemen", "DZ": "Algeria", "US": "United States", "UY": "Uruguay", "YT": "Mayotte",

poll/templates/poll/all.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
<html lang="en">
<canvas id="canvas" width="600" height="600"> error </canvas>
<head>
<title>luch</title>


<link rel="stylesheet" href="{% static 'css/zz.css' %}" type="text/css">
<link rel="icon" href= "{% static 'img/favicon.ico' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> <!-- carusel -->
<link rel="stylesheet" href="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"> <!-- graph -->
<!--script-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script> <!-- graph -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<!--meta-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--<style> img,a[href] { cursor: url(static/img/gun.png), wait; } </style>-->
{% include "poll/navbar1.html" %}

<!---->
</head>

<body id="bootstrap-overrides">
<div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img style="height:50%;margin-top:-100px" src="{% static 'img/pythonorig.jpg' %}" alt="Image">
                <div class="carousel-caption">
                  <h3>Sell $</h3>
                  <p>Money Money.</p>
                </div>
              </div>
              <div class="item">
                <img style="height:50%;margin-top:-100px" src="{% static 'img/js_main.jpg' %}" alt="Image">
                <div class="carousel-caption">
                  <h3>More Sell $</h3>
                  <p>Lorem ipsum...</p>
                </div>
              </div>
            </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="container text-center">
          <div class="container" id="parameters">

              <div class="row">
              <div class="col-sm-10 col-md-5">
                <div class="view overlay z-depth-1-half">
                <div class="well" >
                 <h4>Your ip: <b>{{ ip }}</b></h4>
                </div>
                    <div class="mask rgba-white-light"></div>
                </div>
              </div>
              <div class="col-sm-10 col-md-5">
                <div class="view overlay z-depth-1-half">
                <div class="well">
                 <p><h4>Your port: <b>{{ name_host }}</b></h4></p>
                </div>
                    <div class="mask rgba-white-light"></div>
                </div>
              </div>
              <div class="col-sm-10 col-md-5">
                <div class="well">
                 <p><h4>Country / sity : <b>{{ country }} / {{ sity }}</b></h4></p>

                </div>
                    <div class="mask rgba-white-light"></div>
              </div>
              <div class="col-sm-10 col-md-5">
                <div class="well">
                    <p><h4>Your name : <b>{{ user }}</b></h4></p>

                    <div class="mask rgba-white-light"></div>
                </div>
              </div>
              <div class="col-sm-10 col-md-5">
                <div class="well">
                 <p><h4>Your User Agent : <b>{{ user_agent }}</b></h4></p>
                </div>
                    <div class="mask rgba-white-light"></div>
              </div>
              <div class="col-sm-10 col-md-5">
                <div class="well">
                    <h4>Get or Post : <b>{{ method }}</b></h4>
                </div>
                    <div class="mask rgba-white-light"></div>
              </div>
            </div>
            </div>
          </div>
    <div class="ct-chart ct-golden-section" id="grafic"></div>
          <!-- Footer -->
        <footer class="page-footer font-small mdb-color lighten-3 pt-4">
          <!-- Footer Elements -->
          <div class="contain">

            <!--Grid row-->
            <div class="row">

              <!--Grid column-->
              <div class="col-lg-2 col-md-12 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(73).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-2 col-md-6 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(78).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-2 col-md-6 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(79).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-2 col-md-12 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(81).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-2 col-md-6 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(82).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

              <!--Grid column-->
              <div class="col-lg-2 col-md-6 mb-4">

                <!--Image-->
                <div class="view overlay z-depth-1-half">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(84).jpg" class="img-fluid"
                    alt="">
                  <a href="">
                    <div class="mask rgba-white-light"></div>
                  </a>
                </div>

              </div>
              <!--Grid column-->

            </div>
            <!--Grid row-->

          </div>
          <!-- Footer Elements -->

          <!-- Copyright -->
          <div class="footer-copyright text-center py-3">© 2018 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
          </div>
          <!-- Copyright -->
        </footer>
        <script type="text/javascript" src="{% static 'js/graph.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/canvas.js' %}"></script>
    </div>
</body>

<!--<script>-->
<!--window.onbeforeunload = function() {-->
<!--  return "Данные не сохранены. Точно перейти?";-->
<!--};-->
<!--</script>-->
</html>

poll/templates/poll/article.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap3 %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h5>{{ article.article_date }}</h5>
<h4>{{ article.article_title }}</h4>
<h2>{{ article.article_text }}</h2>
<hr>
{% for comment in comments %}
<h5>{{ comment.comments_text }}</h5>
{% endfor %}


</body>
</html>

poll/templates/poll/articles.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stena</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/articles.css' %}" type="text/css">

<link rel="icon" href= "{% static 'img/favicon.ico' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">


<!--meta-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<header>
 {% include "poll/navbar.html" %}
</header>
<section class="all">
    <h1 class="center">Твоя лента</h1>
    {% for article in articles %}
        <div class="w3-half">
            <div class="card" style="width:60%;">
              <img class="card-img-top" src="{{ article.article_image.url}}">
              <div class="card-body">
                <h4 class="card-title" style="margin-top:0">{{ article.article_date }}</h4>
                <p class="card-text"> ЛАЙКИ{{ article.article_likes }}///\\\ {{ article.article_text }}</p>
                <a href="/articles/get/{{ article.id }}" class="btn btn-primary">{{ article.article_title }}</a>
              </div>
            </div>
        </div>
    {%endfor%}


</section>

<style>

</style>
</html>

poll/templates/poll/contact.html
<html>
<head>
     
    <title>Django</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
                <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
     
    <form action="" method="post">
        <label>Имя</label>
        <input name="name" type="text" value="{{ form.name }}">
 
        <label>Е-mail</label>
        <input name="email" type="text" value="{{ form.email }}">
         
        <label>Сообщение</label>
        <textarea name="message">{{ form.message }}</textarea>
         
        <input type="submit" value="Отправить">
        {% csrf_token %}
    </form>
</body>
</html>

poll/templates/poll/detail.html
<h1>{{ question.question_text }}</h1>
  <style>
   H1 { 
    font-size: 120%; 
    font-family: Verdana, Arial, Helvetica, sans-serif; 
    color: #fff333; 
   }
input:focus {
  background: #FF0000;
}


  </style>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

poll/templates/poll/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

poll/templates/poll/myview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>lesson</title>
</head>

<body>

{{ name }}

<form method="POST" action="basicview/1">
{% csrf_token %}
<input type="text" name="textfield">

<button type="submit">Upload text</button>
</form>
</body>
</html>

poll/templates/poll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>